development:
  adapter: postgresql
  encoding: unicode
  database: journey_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: journey_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
